#!/usr/bin/env bash
set -eo pipefail

#This script runs all the necessary installation scripts in the "scripts/" directory to set up the environment for the project.
chmod +x installationScripts/*.sh

case "$1" in
    --install)
		bash installationScripts/InstallDependencies.sh
		bash installationScripts/InstallDBeaver.sh
		bash installationScripts/Apache.sh
		bash installationScripts/Caddy.sh
		bash installationScripts/MySQL.sh
        ;;
    --uninstall)
        ;;
    *)
		echo "Usage: $0 [--install|--uninstall]"
		exit 1
esac